# -*- coding: utf-8 -*-
"""data exploration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xbb_eBh1sPEMjIfVe29OjL-9lk0u-kTA
"""

import os
import pandas as pd

path = "combined_csv.csv"
data = pd.read_csv(path, error_bad_lines=False)
data = data[data.evaluatedAt != " did not evaluate"]
data = data[data.questionid.str.strip() == 'Q1']

